version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - /home/dockerProjects/company-profile:/home/dockerProjects/company-profile
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=horus_danang_db
      - MYSQL_USER=adminprogrammer
      - MYSQL_PASSWORD=123456
    working_dir: /home/dockerProjects/company-profile
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
